package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EditionResultsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditionResultsAllPropertiesEquals(EditionResults expected, EditionResults actual) {
        assertEditionResultsAutoGeneratedPropertiesEquals(expected, actual);
        assertEditionResultsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditionResultsAllUpdatablePropertiesEquals(EditionResults expected, EditionResults actual) {
        assertEditionResultsUpdatableFieldsEquals(expected, actual);
        assertEditionResultsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditionResultsAutoGeneratedPropertiesEquals(EditionResults expected, EditionResults actual) {
        assertThat(actual)
            .as("Verify EditionResults auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditionResultsUpdatableFieldsEquals(EditionResults expected, EditionResults actual) {
        assertThat(actual)
            .as("Verify EditionResults relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditionResultsUpdatableRelationshipsEquals(EditionResults expected, EditionResults actual) {
        assertThat(actual)
            .as("Verify EditionResults relationships")
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()));
    }
}
